apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer  # Exposes the service externally
  selector:
    app: my-app  # Matches the deployment labels
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 80  # Container port

